// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vFR2WgCdBsyIIL1k9teQNZTi4ZAzhtg',
    appId: '1:943998527706:web:667696d27b918227b29de3',
    messagingSenderId: '943998527706',
    projectId: 'obra-7ebd9',
    authDomain: 'obra-7ebd9.firebaseapp.com',
    databaseURL: 'https://obra-7ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'obra-7ebd9.firebasestorage.app',
    measurementId: 'G-XYH593993R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvo-N3zOw-lTp0pqH-mswMF5FYGCn87Q',
    appId: '1:943998527706:android:29050b61e18cad85b29de3',
    messagingSenderId: '943998527706',
    projectId: 'obra-7ebd9',
    databaseURL: 'https://obra-7ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'obra-7ebd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehAfMGic-Jlis2XzysfK9wkkA52-8lHY',
    appId: '1:943998527706:ios:bce562f2af7ddcf7b29de3',
    messagingSenderId: '943998527706',
    projectId: 'obra-7ebd9',
    databaseURL: 'https://obra-7ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'obra-7ebd9.firebasestorage.app',
    iosBundleId: 'com.vstecnology.maodeobra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDehAfMGic-Jlis2XzysfK9wkkA52-8lHY',
    appId: '1:943998527706:ios:bce562f2af7ddcf7b29de3',
    messagingSenderId: '943998527706',
    projectId: 'obra-7ebd9',
    databaseURL: 'https://obra-7ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'obra-7ebd9.firebasestorage.app',
    iosBundleId: 'com.vstecnology.maodeobra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vFR2WgCdBsyIIL1k9teQNZTi4ZAzhtg',
    appId: '1:943998527706:web:cc4bf4b959815341b29de3',
    messagingSenderId: '943998527706',
    projectId: 'obra-7ebd9',
    authDomain: 'obra-7ebd9.firebaseapp.com',
    databaseURL: 'https://obra-7ebd9-default-rtdb.firebaseio.com',
    storageBucket: 'obra-7ebd9.firebasestorage.app',
    measurementId: 'G-YBPBPDLT8M',
  );

}